### PR TITLE
Disable Enarxbot

### LINKED ISSUE #1228: Disable Enarxbot

### PR DESCRIPTION
**Pull request by nickvidal**
This PR disables Enarxbot by default at `enarx/enarx`. I left the option of triggering it if a pull request is made against the `enarxbot` branch.

Closes #1228 

I wasn't able to figure out how to do **one** PR against **multiple** repositories. Should I file multiple PRs?

Signed-off-by: Nick Vidal <nick@profian.com>

### CODE REVIEW

**Comment by rvolosatovs** [comment]
> I wasn't able to figure out how to do one PR against multiple repositories. Should I file multiple PRs?

That's not possible, unfortunately. But it definitely helps to inter-reference them (that does work across repos)

**Review by rvolosatovs — COMMENTED** [review]
Shouldn't we just remove the file altogether?

**Comment by nickvidal** [comment]
> Shouldn't we just remove the file altogether?

Yes, that's what I thought at first, but left the option of running enarxbot if desired.

**Comment by npmccallum** [comment]
@nickvidal I think we want to remove it completely. We can always look back in the git history if we need.

**Review by npmccallum — APPROVED** [review]

**Pull request merged**
