### PR TITLE
refactor(kvm): open code kvm_builder_map

### PR DESCRIPTION
**Pull request by jarkkojs**
A preparatory step for adding support for kvm_userspace_memory_ext.

Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>

### CODE REVIEW

**Comment by jarkkojs** [comment]
Link: #2266

**Comment by jarkkojs** [comment]
It is easier to implement and review UPM support when the creation sites have been "localized" .

**Comment by Freax13** [comment]
The commit mentioned at https://github.com/enarx/enarx/pull/2453#issuecomment-1398494380 was created as part of this pr.

**Comment by haraldh** [comment]
@jarkkojs ! fix the failing DCO check (required)!

**Review by haraldh — CHANGES_REQUESTED** [review]
LGTM, but the DCO check (required) is failing, because the commit message is missing an `S` in the the `Signed-off`

**Comment by jarkkojs** [comment]
I think we can close this given that other PR's supersede this one.

**Pull request closed without merging**
