### PR TITLE
Added PR templates

### LINKED ISSUE #39: Pull Request Templates
We might want to have some pull request templates.

### PR DESCRIPTION
**Pull request by shravi24**
Closes enarx/.github#18

### CODE REVIEW

**Review by platten — COMMENTED** [review]
@shravi24, could you please provide some background on why there are so many PR templates?  Was the goal to provide alternatives?

**Comment by shravi24** [comment]
> @shravi24, could you please provide some background on why there are so many PR templates? Was the goal to provide alternatives?

Yes, the idea was to provide a choice of templates.

**Comment by platten** [comment]
I would recommend to move this the pull request template to [enarx/.github](https://github.com/enarx/.github)

**Comment by platten** [comment]
Closing PR, pending move to `enarx/.github` repository

**Comment by shravi24** [comment]
> Closing PR, pending move to `enarx/.github` repository

Moved this the pull request to [`enarx/.github/pull/19`](https://github.com/enarx/.github/pull/19)

**Pull request closed without merging**
