### PR TITLE
support running on the SEV-SNP v8 patches

### PR DESCRIPTION
**Pull request by Freax13**
This pr adds the necessary changes to run Enarx on the new SEV-SNP v8 host patches. It's based on pr  #2453 for the v7 patches.

This time only one additional patch is required:
https://github.com/Freax13/linux/commit/82799c49b7dbc50c1ca20b39dd68491bb060045e

Based on #2453

### CODE REVIEW

**Comment by jethrogb** [comment]
Note this kernel patch is required on top of v8:
```
diff --git a/arch/x86/kvm/svm/sev.c b/arch/x86/kvm/svm/sev.c
index 42f8a5b7c706..3ae4a29b12a5 100644
--- a/arch/x86/kvm/svm/sev.c
+++ b/arch/x86/kvm/svm/sev.c
@@ -4062,7 +4062,7 @@ static int sev_handle_vmgexit_msr_protocol(struct vcpu_svm *svm)
                vcpu->run->vmgexit.ghcb_msr = control->ghcb_gpa;
                vcpu->arch.complete_userspace_io = snp_complete_psc_msr_protocol;
 
-               ret = -1;
+               ret = 0;
                break;
        case GHCB_MSR_TERM_REQ: {
                u64 reason_set, reason_code;
```

**Comment by rjzak** [comment]
@Freax13 of you're still interested in Enarx, could we work together to get support in for the latest SNP patches? I just read about V10 on [Phoronix](https://www.phoronix.com/news/AMD-SEV-SNP-Intel-TDX-Journey). I have the hardware, just not so much kernel experience. 
CC: @nickvidal

**Comment by Freax13** [comment]
Yeah, sure. I also have some hardware. I'll get started on adding support for the v10 patches.

**Comment by rjzak** [comment]
Sweet. Could you also share a working kernel so I can test and get the CI SNP machine back up and running?

**Comment by Freax13** [comment]
> Sweet. Could you also share a working kernel so I can test and get the CI SNP machine back up and running?

The last few versions needed some additional patches  on top of what AMD has provided. I don't know yet if we'll need additional patches on top of v10. I can provide you with a kernel once I've updated enarx to work with the new v10 patches.

**Comment by rjzak** [comment]
Will your new Enarx PR need the other SNP PRs merged? How can you send a kernel, Dropbox or Google Drive?
Also, my email is richard.j.zak@gmail.com if that's easier than GitHub comments for communicating.

**Comment by Freax13** [comment]
> Will your new Enarx PR need the other SNP PRs merged?

It will likely be based on them, but will supersede them.

> How can you send a kernel, Dropbox or Google Drive? Also, my email is [richard.j.zak@gmail.com](mailto:richard.j.zak@gmail.com) if that's easier than GitHub comments for communicating.

We'll see. I'll reach out to you once I'm done. I could also provide you a git branch (ideally on https://github.com/enarx/linux) that you could pull and install.

**Comment by Freax13** [comment]
Superseded by #2552

**Pull request closed without merging**
