### PR TITLE
Add conferences issue template

### PR DESCRIPTION
**Pull request by axelsimon**

### CODE REVIEW

**Comment by npmccallum** [comment]
@mbestavros This branch has a merge commit but tests are passing. Tests need to fail.

**Comment by mbestavros** [comment]
@npmccallum We don't currently have any such test. I've created an issue to implement one and self-assigned it here: https://github.com/enarx/enarx/issues/51

**Comment by axelsimon** [comment]
I created this Pull Request using Github default web options. We might want to configure something in the preferences to disallow merge commits then.

**Comment by axelsimon** [comment]
Closing this and redoing it clean.

**Pull request closed without merging**
