### PR TITLE
Fix guidance comment formatting in conferences template

### PR DESCRIPTION
**Pull request by axelsimon**
And turn more things into bullet points.

### CODE REVIEW

**Comment by axelsimon** [comment]
Further to this, as we've already mentioned before, it doesn't really make sense to run most (all?) of these tests on things such as issue templates.
It's probably a safe bet to exclude `.github` or at least `.github/ISSUE_TEMPLATE` from the tests.

I'll try to force-push to see if it goes through this time.

**Comment by mbestavros** [comment]
> Further to this, as we've already mentioned before, it doesn't really make sense to run most (all?) of these tests on things such as issue templates.
> It's probably a safe bet to exclude `.github` or at least `.github/ISSUE_TEMPLATE` from the tests.

I think this was more of an issue when we were running tests pre-push, and tests needed to pass in order to even get your stuff up to the cloud -- which wasted time.

While I don't disagree with your comment @axelsimon, I think it's much less of an issue now (barring freak outages like this).

**Comment by axelsimon** [comment]
I'm also considering this from a frugality perspective: there is little point in using CPU time and by extension energy for tests that are unrelated to the changes at play. Automating testing is a great thing for ensuring quality over time, but it should be balanced with the need to spin up resources all the time.

Two more things. I mistakenly created a branch on the Enarx repo and not in my fork. So i'd rather not (force) push any further to the Enarx repo. But the good news is that there's simply a [rerun jobs](https://github.com/enarx/enarx/pull/305/checks?check_run_id=495563604) button on the "checks" page, which makes force pushing unnecessary. The bad news is that `misc-diagrams` is still failing. There are no diagrams here, i suggest we rebase and merge and be done with it.
Do you agree?

**Comment by mbestavros** [comment]
I just realized "rerun jobs" exists. Neat!

Having done that, it looks like `misc-diagrams` passes now. So I think we're good to go.

And yes -- agreed again. We shouldn't be spinning up resources we don't need to be. It's a question of how we prioritize it.

**Pull request merged**
