### PR TITLE
Add conference issue template

### PR DESCRIPTION
**Pull request by axelsimon**
Issue template for conference, automatically adds the 'conference' label.

### CODE REVIEW

**Comment by axelsimon** [comment]
This PR should be clean, thanks to @mbestavros's help. Let me know if anything needs to be changed.

**Comment by npmccallum** [comment]
@axelsimon This mostly looks good. However, can we use ISO 8601 for dates?

**Comment by axelsimon** [comment]
@mbestavros and i discussed using ISO format dates (which i usually use everywhere), but i argued against it for two reasons, in this case:
- readability: 2020-01-13 is harder on the eyes than 13 January 2020
- displaying a range

I've now just learned ISO 8601 has a solution for ranges :)

For the sake of being able to automate tagging and closing conference issues in the future by easily parsing dates, i will switch the dates to ISO 8601.

**Comment by axelsimon** [comment]
@mbestavros and i discussed using ISO format dates (which i usually use everywhere), but i argued against it for two reasons, in this case:
- readability: 2020-01-13 is harder on the eyes than 13 January 2020
- displaying a range

I've now just learned ISO 8601 has a solution for ranges :)

For the sake of being able to automate tagging and closing conference issues in the future by easily parsing dates, i will switch the dates to ISO 8601.

**Comment by npmccallum** [comment]
@axelsimon Any update on this?

**Comment by axelsimon** [comment]
Yes, as the `master` branch has moved forward, working on updating my branch cleanly, without getting a merge commit.

**Comment by axelsimon** [comment]
If all is right, i updated my branch to include a new commit that modifies the issue template to use the ISO 8601 format for dates, answering @npmccallum requested change.
Let me know if this is ok now :)

**Pull request merged**
