### PR TITLE
build: add rusty-tags.vi to .gitignore

### PR DESCRIPTION
**Pull request by jarkkojs**
Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>

### CODE REVIEW

**Review by rvolosatovs — COMMENTED** [review]
I think this is something that should go in your global `git` config (`core.excludesfile`), but given that we also have `.idea` and `.vscode` here (which IMO also do not belong), I guess that's fine?

**Comment by jarkkojs** [comment]
> I think this is something that should go in your global `git` config (`core.excludesfile`), but given that we also have `.idea` and `.vscode` here (which IMO also do not belong), I guess that's fine?

I don't think this causes anyone any harm.

**Comment by rvolosatovs** [comment]
> > I think this is something that should go in your global `git` config (`core.excludesfile`), but given that we also have `.idea` and `.vscode` here (which IMO also do not belong), I guess that's fine?
> 
> I don't think this causes anyone any harm.

Sure, that's why I don't mind merging, this, but let's see what others think.
I don't know if we want to have maintain a list of various environment-specific files here (e.g. `.DS_Store` could be one example of a file that should probably be included here if we do that, probably `tags` for ctags-style tags, vim temporary files, maybe something for emacs? kakoune? etc. etc.)

**Comment by jarkkojs** [comment]
@rvolosatovs I agree that a global setting is better because otherwise same would have to spread to all repositories, so I've decided to close this.

**Pull request closed without merging**
