### PR TITLE
feat(sev): upm

### PR DESCRIPTION
**Pull request by jarkkojs**
Closes: #2266

### CODE REVIEW

**Comment by Freax13** [comment]
@jarkkojs are you still working on this? If not, I'd like to pick this up. I already got a hacked-up prototype working, I would only have to clean it up.

**Comment by jarkkojs** [comment]
@Freax13 I'm working on it now. It hasn't made any sense to work on it before UPM v10 and SNP v7 patch sets were not out.

As far as your work goes, it depends on what it is compatible with.

**Comment by Freax13** [comment]
[My work](https://github.com/Freax13/enarx/tree/feat/sev/upm) is compatible with the v7 patch set. It requires one additional patch: https://github.com/Freax13/linux/commit/b910c2271c4dac1353443fca98c7647414f8eebc. I'm not 100% if that patch is required though.

**Comment by jarkkojs** [comment]
> [My work](https://github.com/Freax13/enarx/tree/feat/sev/upm) is compatible with the v7 patch set. It requires one additional patch: [Freax13/linux@b910c22](https://github.com/Freax13/linux/commit/b910c2271c4dac1353443fca98c7647414f8eebc). I'm not 100% if that patch is required though

Could you write a description so that it is pickable to downstream tree? Just explaining reasoning for the change like any kernel commit. Especially if it is a dep for your changes.

Enarx was not updated because of v7 was out only at the end of the year. I'm working on SNP platform init right now for kernel, so it is absolutely find for you to do the Enarx PR.

**Comment by jarkkojs** [comment]
> > [My work](https://github.com/Freax13/enarx/tree/feat/sev/upm) is compatible with the v7 patch set. It requires one additional patch: [Freax13/linux@b910c22](https://github.com/Freax13/linux/commit/b910c2271c4dac1353443fca98c7647414f8eebc). I'm not 100% if that patch is required though
> 
> Could you write a description so that it is pickable to downstream tree? Just explaining reasoning for the change like any kernel commit. Especially if it is a dep for your changes.
> 
> Enarx was not updated because of v7 was out only at the end of the year. I'm working on SNP platform init right now for kernel, so it is absolutely find for you to do the Enarx PR.

I can pick that fix to enarx/linux tree if it makes sense (so that I can eventually test your change).

There might be some cosmetic stuff that I'd like to see from this PR. Namely `map_sallyports` change which should have been separated to a separate patch.

**Comment by Freax13** [comment]
> > > [My work](https://github.com/Freax13/enarx/tree/feat/sev/upm) is compatible with the v7 patch set. It requires one additional patch: [Freax13/linux@b910c22](https://github.com/Freax13/linux/commit/b910c2271c4dac1353443fca98c7647414f8eebc). I'm not 100% if that patch is required though
> > 
> > 
> > Could you write a description so that it is pickable to downstream tree? Just explaining reasoning for the change like any kernel commit. Especially if it is a dep for your changes.
> > Enarx was not updated because of v7 was out only at the end of the year. I'm working on SNP platform init right now for kernel, so it is absolutely find for you to do the Enarx PR.
> 
> I can pick that fix to enarx/linux tree if it makes sense (so that I can eventually test your change).
> 
> There might be some cosmetic stuff that I'd like to see from this PR. Namely `map_sallyports` change which should have been separated to a separate patch.

Alright, will do.

**Comment by jarkkojs** [comment]
I created #2448, which is essentially what I meant. However it is implemented this is IMHO a good preparatory step. Sallyport mappings is orthogonal functionality.

**Comment by jarkkojs** [comment]
```
commit 2bcf7ea5cb0ff1d925878a5f2e293df6c0511caa (HEAD -> feat/sev/upm2, origin/feat/sev/upm2)
Author: Jarkko Sakkinen <jarkko@profian.com>
Date:   Tue Jan 10 03:23:02 2023 +0000

    refactor(kvm): normalize `kvm_userspace_memory_region` creation

    `kvm_userspace_memory_region` creation does not follow a consistent
    pattern:

    * `backend::kvm::Keep::map()` directly creates an instance.
    * `backend::{kvm,sev}::builder::Builder::map()` use a delegate
      called `kvm_builder_map()`.

    Normalize call pattern to the former. This is a better starting point to
    implement support for `kvm_userspace_memory_region`.

    Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>
```

**Pull request closed without merging**
