### PR TITLE
fix[sgx]: attestation test

### PR DESCRIPTION
**Pull request by jarkkojs**
Check that SGX is enabled before running the test.

Closes: https://github.com/enarx/enarx/issues/1402
Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>

### CODE REVIEW

**Review by haraldh — APPROVED** [review]

**Comment by haraldh** [comment]
@rvolosatovs it should only be used for tests then... and should be probably named: `test_can_use_sgx` or so

**Comment by jarkkojs** [comment]
updated:
```
    #[test]
    fn request_target_info() {
        use crate::backend::sgx::data::dev_sgx_enclave;
        use std::path::Path;

        if !dev_sgx_enclave().pass || !Path::new(AESM_SOCKET).exists() {
            return;
        }

        let output = [1u8; SGX_TI_SIZE];
        assert_eq!(
            get_attestation(0, 0, output.as_ptr() as usize, output.len()).unwrap(),
            SGX_TI_SIZE
        );
    }
```

**Comment by jarkkojs** [comment]
Updated based on @rvolosatovs feedback.`build.rs` has now `has_sgx`.

**Review by rvolosatovs — DISMISSED** [review]

**Comment by rvolosatovs** [comment]
Please make sure tests pass, otherwise LGTM

**Review by npmccallum — APPROVED** [review]

**Pull request merged**
