### PR TITLE
Fixing CLI Log for misleading version

### LINKED ISSUE #1098: enarx binary reports wrong or misleading version when logging
v0.1.2 reports `version 0.1.0` in first log output.

`enarx --version` outputs (correctly) `enarx 0.1.2`.

Observed:
```
[mikecamel@coffeelake timestamp]$ ENARX_BACKEND=sgx enarx run target/wasm32-wasi/release/timestamp.wasm 
[INFO  wasmldr] version 0.1.0 starting up
...
```

Expected 
```
[mikecamel@coffeelake timestamp]$ ENARX_BACKEND=sgx enarx run target/wasm32-wasi/release/timestamp.wasm 
[INFO  wasmldr] version 0.1.0 starting up
...
```

Suggest auto-filling from a known file for all possible outputs of versioning (and other related metadata).

### PR DESCRIPTION
**Pull request by Deepansharora27**
Signed-off-by: Deepanshu Arora <deepansharora27@gmail.com>

Closes #1098

### CODE REVIEW

**Comment by Deepansharora27** [comment]
@npmccallum I have made the required changes 
Apologies for not doing a force-push on the previous one
It's just that earlier when I was a part of a side project, I was not advised to do force-push on a branch there so since that time this thought subconsciously got embedded in my mind. 

I will keep this in mind from future 
I have also done a `cargo fmt` check before making the commit 

If any other change is required, then please let me know

**Comment by Deepansharora27** [comment]
I also want your feedback on the Commit Message

**Comment by Deepansharora27** [comment]
Although I did a `cargo fmt` check before making the commit , it's showing me that 
`lint / cargo fmt (wasmldr) (pull_request)` failed. 
Can you guide me what can be the possible issue here ?

**Comment by npmccallum** [comment]
@Deepansharora27 https://github.com/enarx/enarx/runs/5038220543?check_suite_focus=true#step:4:11

It wants you to remove one of the blank lines.

**Comment by Deepansharora27** [comment]
@npmccallum This Pull Request got closed automatically. 
I was just making a commit with the Required changes via force push and it resulted into this

**Pull request closed without merging**
