### PR TITLE
ci: various improvements in relation to `--workspace` support

### PR DESCRIPTION
**Pull request by rvolosatovs**
Blocked by #2423

### CODE REVIEW

**Comment by haraldh** [comment]
Please also coverage.yml

**Comment by haraldh** [comment]
And adjust `.codecov.yml` line 3 with the number of matrix jobs in the coverage workflow

**Review by haraldh — CHANGES_REQUESTED** [review]

**Comment by rvolosatovs** [comment]
Looks like this PR is blocked on changes to https://github.com/profianinc/infra-terraform/blob/be9bd1afd473dfdb9087551ed883b5d2dac59ff1/github_branchprotections_enarx.tf#L60-L96 @puiterwijk ?

**Comment by bstrie** [comment]
Does every clippy check need to be its own action? Once one action has already done a full `cargo check --workspace`, the subsequent `cargo check -p enarx-shim-kvm -p enarx-shim-sgx --target x86_64-unknown-none` takes about 4 seconds, which doesn't seem worth the compute/transfer costs of spinning up a separate runner just do do those.

**Review by haraldh — APPROVED** [review]

**Pull request merged**
