### PR TITLE
fix(shim-sgx): update FSGSBASE in arch_prctl() correctly

### PR DESCRIPTION
**Pull request by jarkkojs**
Closes: #1558
Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>

### CODE REVIEW

**Review by haraldh — CHANGES_REQUESTED** [review]
This is not correct and sets FS and GS in the shim context.

**Comment by jarkkojs** [comment]
> This is not correct and sets FS and GS in the shim context.

The existing code does not set them, they're unconditionally taken from TCS.

**Comment by jarkkojs** [comment]
> > This is not correct and sets FS and GS in the shim context.
> 
> The existing code does not set them, they're unconditionally taken from TCS.

Applies to both EENTER and ERESUME:

```
TMP_FSBASE := (DS:RBX).OFSBASE + TMP_SECS.BASEADDR;
TMP_FSLIMIT := (DS:RBX).OFSBASE + TMP_SECS.BASEADDR + (DS:RBX).FSLIMIT;
TMP_GSBASE := (DS:RBX).OGSBASE + TMP_SECS.BASEADDR;
TMP_GSLIMIT := (DS:RBX).OGSBASE + TMP_SECS.BASEADDR + (DS:RBX).GSLIMIT;
```

**Comment by haraldh** [comment]
I'll leave it to @npmccallum to explain again all the SSA level changes happening on a syscall.

**Comment by jarkkojs** [comment]
> I'll leave it to @npmccallum to explain again all the SSA level changes happening on a syscall.

Happy to hear that, since I did this PR to poke a bit before I start pushing anything larger. I was planning to limit this further to allow setting only to the dynamically allocated range, so in that sense this is really important to understand.

**Comment by jarkkojs** [comment]
@npmccallum For this do not eagerly want to get this merged, but I do want to know what is wrong, because I don't understand :-) It's one way to formalize a question kind of.

**Comment by npmccallum** [comment]
@jarkkojs  the handler is operating in CSSA=1. The ssa reference here is to CCCS=0. We can modify it and then when we do ERESUME, the CPU restores its context to the new values we put into the SSA.

**Comment by jarkkojs** [comment]
@npmccallum I might be wrong but looking at pseudo-code from SDM, fsbase and gsbase are always pulled from TCS. You can write other values to SSA but I don't think they have effect. That's why there was also push from SGX side to get WRFSBASE et al supported in the kernel.

**Comment by jarkkojs** [comment]
From `ERESUME` description in the SDM: _"new values are constructed using TCS.OFSBASE/GSBASE (32 and 64-bit mode) and TCS.OFSLIMIT/GSLIMIT (32-bit mode only)."_

**Comment by npmccallum** [comment]
I'm open to my implementation being faulty. However, I think that means we need a musl libc that supports WRFSBASE. Is that correct?

**Comment by jarkkojs** [comment]
> I'm open to my implementation being faulty. However, I think that means we need a musl libc that supports WRFSBASE. Is that correct?

See e.g. https://github.com/occlum/occlum/issues/39. So I guess the answer is yes.

**Pull request closed without merging**
