### PR TITLE
fix(helper/test-enarx.sh): require bash

### PR DESCRIPTION
**Pull request by haraldh**
Signed-off-by: Harald Hoyer <harald@profian.com>

### CODE REVIEW

**Comment by bstrie** [comment]
What does this fix?

**Comment by haraldh** [comment]
> What does this fix?

@bstrie `${ENARX_BIN[0]}` is not recognized by a posix shell

**Comment by haraldh** [comment]
@bstrie if `/bin/sh` is not a symlink to `/bin/bash` the tests will fail

**Review by rvolosatovs — APPROVED** [review]
LGTM, but we really *have* to use bash here?

**Pull request merged**
