### PR TITLE
chore: bump rust toolchain to nightly-2022-07-14

### PR DESCRIPTION
**Pull request by platten**
Addresses `sparse-registry` [publishing error](https://github.com/rust-lang/cargo/issues/10828).
This may invalidate #2058 

Signed-off-by: Paul Pietkiewicz <paul@profian.com>

### CODE REVIEW

**Comment by platten** [comment]
@bstrie can you take a look when you have a moment? Wanted to bump the toolchain to ensure we address the `sparse-registries` issue encountered, and got multiple test failures.

**Comment by haraldh** [comment]
@platten the sev and kvm failures are because `rivest` didn't load the `kvm-amd` module automatically.

**Comment by platten** [comment]
@haraldh if you have a moment, and if it wouldn't require too much effort, any chance you could look into updating the miri tests to make this pass? Thanks!

**Comment by haraldh** [comment]
> @haraldh if you have a moment, and if it wouldn't require too much effort, any chance you could look into updating the miri tests to make this pass? Thanks!

@platten not today..  just disable the tests for now, or remove them from the list to be required.

**Comment by platten** [comment]
> > @haraldh if you have a moment, and if it wouldn't require too much effort, any chance you could look into updating the miri tests to make this pass? Thanks!
> 
> @platten not today.. just disable the tests for now, or remove them from the list to be required.

sallyport miri tests were removed from required tests temporarily.

**Comment by bstrie** [comment]
Superseded by https://github.com/enarx/enarx/pull/2067 .

**Pull request closed without merging**
