### PR TITLE
Fixing CLI Log Issue

### LINKED ISSUE #1098: enarx binary reports wrong or misleading version when logging
v0.1.2 reports `version 0.1.0` in first log output.

`enarx --version` outputs (correctly) `enarx 0.1.2`.

Observed:
```
[mikecamel@coffeelake timestamp]$ ENARX_BACKEND=sgx enarx run target/wasm32-wasi/release/timestamp.wasm 
[INFO  wasmldr] version 0.1.0 starting up
...
```

Expected 
```
[mikecamel@coffeelake timestamp]$ ENARX_BACKEND=sgx enarx run target/wasm32-wasi/release/timestamp.wasm 
[INFO  wasmldr] version 0.1.0 starting up
...
```

Suggest auto-filling from a known file for all possible outputs of versioning (and other related metadata).

### PR DESCRIPTION
**Pull request by Deepansharora27**
Signed-off-by: Deepanshu <deepansharora27@gmail.com>

Closes #1098

### CODE REVIEW

**Comment by Deepansharora27** [comment]
Aplologies @npmccallum 
Since last 2 times, I made some blunder mistakes and the reason is this:

Everytime I was making a formatting change, I had this extension installed in my editor which would re-format the changes that I made and thus it was causing the issue again and again

This time, I have doubled checked everything. 
Sorry for taking your time again

**Review by Deepansharora27 — COMMENTED** [review]
@npmccallum If you could review it, I'll be glad

**Comment by Deepansharora27** [comment]
Thanks a lot @npmccallum. All the Checks have passed now. 

This is going to be my first and last mistake. 
Thanks a lot for your Patience.

**Review by haraldh — APPROVED** [review]

**Comment by Deepansharora27** [comment]
Thanks @haraldh !!

**Pull request merged**
