### PR TITLE
feat(sgx): EACCEPT{COPY}

### PR DESCRIPTION
**Pull request by jarkkojs**

### CODE REVIEW

**Review by npmccallum — CHANGES_REQUESTED** [review]
This probably belongs in the https://github.com/enarx/sgx crate. Specifically, it probably belongs in this file: https://github.com/enarx/sgx/blob/main/src/page/sinfo.rs.

**Comment by npmccallum** [comment]
@jarkkojs Also note that we have constants for the leaf instructions already: https://docs.rs/sgx/0.3.0/sgx/enclu/index.html

**Comment by jarkkojs** [comment]
> This probably belongs in the https://github.com/enarx/sgx crate. Specifically, it probably belongs in this file: https://github.com/enarx/sgx/blob/main/src/page/sinfo.rs.

What about Report and TargetInfo?

**Comment by npmccallum** [comment]
@jarkkojs Link?

**Comment by npmccallum** [comment]
@jarkkojs Yes. It probably makes sense to move them to `sgx` immediately after the release.

**Comment by jarkkojs** [comment]
https://github.com/enarx/sgx/pull/62

**Pull request closed without merging**
