### PR TITLE
Transfer SEV documentation to the 'sev' crate

### PR DESCRIPTION
**Pull request by connorkuehl**
Related: https://github.com/enarx/sev/issues/17

- Transfer SEV documentation to the 'sev' crate
- Remove cargo-make Makefile

### CODE REVIEW

**Review by npmccallum — APPROVED** [review]

**Review by lkatalin — APPROVED** [review]

**Comment by jethrogb** [comment]
cargo make is still mentioned in the README

**Comment by connorkuehl** [comment]
@jethrogb do you have any interest in opening a PR for that?

**Comment by jethrogb** [comment]
Well I don't really know what to put in it's place. I'd expect some basic "here's how to get something running" there.

**Comment by connorkuehl** [comment]
Okay! I'll take care of it. If you'd like, I can credit you in the commits if you're comfortable with sharing a `Reported-by:` trailer here

for example: `Reported-by: Connor Kuehl <ckuehl@redhat.com>`

**Comment by jethrogb** [comment]
That's ok

**Pull request merged**
